### ISSUE TITLE
`make_dataclass` for `Pytree`

### ISSUE THREAD

**Issue by pablo2909** [cgarciae/simple-pytree#13]
Hi,

Thank you for this super cool library. 

I was wondering if there is something similar to `make_dataclass` from `dataclasses` [here](https://docs.python.org/3/library/dataclasses.html#dataclasses.make_dataclass) ? In my case it would be super useful to build some custom metrics based on a config file.

Thanks again :)

**Comment by pablo2909** [comment]
Playing a bit with it, I'm able to do this but I'm not sure this is the way to go:

```python
import dataclasses as dc
from simple_pytree import dataclass, Pytree, static_field

A = dc.make_dataclass('A',
                   [('x', int),
                     'y',
                    ('z', int, static_field(default=5))],
                   )

@dataclass
class B(A, Pytree):
    ...

B(1, 2, 3)

```

**Comment by cgarciae** [comment]
Hey @pablo2909, I think your approach is correct and should be supported. It currently doesn't work but I created #14 fix it.

**Comment by cgarciae** [comment]
Fixed in `0.2.2`

**Comment by pablo2909** [comment]
Thank you for the super quick response and fix :)

Could you please elaborate on what did not work and the fix you brought ? Because the MWE I posted was working for me. 

Thanks again ! This library is really super useful :)

**Comment by cgarciae** [comment]
No problem! The resulting pytree was not making`z` a static field.
